name: taukeet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  location: ^5.0.3
  geocoding: ^2.1.0
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  app_settings: ^5.0.0
  flutter_form_builder: ^9.1.1
  adhan: ^2.0.0
  showcaseview: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
  fonts:
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
